title: Flip webcards met lekkernijen
hero_image: images/banner.png
description: Maak een set interactieve kaarten die uitleg geven over zoete lekkernijen van over de hele wereld.
meta_title: CSS-tutorial | Leer webontwikkeling |Flip webcards met lekkernijen
meta_description: In deze CSS-handleiding leer je webontwikkeling met de Raspberry Pi Foundation. Gebruik CSS animaties om interactieve kaarten te maken die omdraaien.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Inleiding
  - 
    title: Maak je kaart
  - 
    title: Draai je kaart om
    completion: engaged
  - 
    title: Stijl je kaart
  - 
    title: Kies je lettertype
    completion: internal
  - 
    title: Reflectie
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion: external
  - 
    title: Verbeter je project
  - 
    title: Wat kun je verder nog doen?
