name: 'Flip treat webcards'
identifier: 'flip-treat-webcards-complete'
type: 'html'
components:
  - name: 'index'
    extension: 'html'
    location: 'index.html'
    index: 0
    default: true
  - name: 'animation'
    extension: 'css'
    location: animation.css
    index: 1
    default: false    
  - name: 'style'
    extension: 'css'
    location: style.css
    index: 2
    default: false
  - name: 'default'
    extension: 'css'
    location: default.css
    index: 3
    default: false
image:
  - "BaraBrith.png"
  - "Breskvice01.png"
  - "Breskvice02.png"
  - "Brigadeiro.png"
  - "Dango01.png"
  - "Dango02.png"
  - "DatePalm01.png"
  - "DatePalm02.png"
  - "Eclair.png"
  - "FairyBread.png"
  - "FrenchFancy.png"
  - "Halva.png"
  - "Jalebi.png"
  - "Knafeh.png"
  - "Ladoo.png"
  - "LapisSarawak01.png"
  - "LapisSarawak02.png"
  - "LollyCake.png"
  - "Maejakgwa01.png"
  - "Maejakgwa02.png"
  - "Mandazi.png"
  - "MapleLeafBiscuit.png"
  - "Oliebollen.png"
  - "PartyRing.png"
  - "TimTams.png"
  - "Zarda.png"