title: Flip treat webcards
hero_image: images/banner.png
description: Create a set of interactive cards that tell people about sweet treats from around the world.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - 
    title: Introduction
  - 
    title: Create your card
  - 
    title: Flip your card
    completion: engaged
  - 
    title: Style your card
  - 
    title: Choose your font
    completion: internal
  - 
    title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion: external
  - 
    title: Upgrade your project
  - 
    title: What next?
